### ISSUE TITLE
game crashes when emitter is broken or receiver placed

### ISSUE THREAD

**Issue by warlock1984** [MrMelon54/wireless-redstone-fabric#1]
[crash-2021-08-28_13.00.47-server.txt](https://github.com/MrMelon54/wireless-redstone-fabric/files/7071203/crash-2021-08-28_13.00.47-server.txt)
[crash-2021-08-28_13.06.04-server.txt](https://github.com/MrMelon54/wireless-redstone-fabric/files/7071204/crash-2021-08-28_13.06.04-server.txt)
[crash-2021-08-28_13.30.28-server.txt](https://github.com/MrMelon54/wireless-redstone-fabric/files/7071205/crash-2021-08-28_13.30.28-server.txt)
[crash-2021-08-28_13.35.15-server.txt](https://github.com/MrMelon54/wireless-redstone-fabric/files/7071206/crash-2021-08-28_13.35.15-server.txt)
[crash-2021-08-28_20.02.36-server.txt](https://github.com/MrMelon54/wireless-redstone-fabric/files/7071207/crash-2021-08-28_20.02.36-server.txt) here some logs single game

**Comment by mrmelon54** [comment]
Which version of the mod are you using?

**Comment by mrmelon54** [comment]
~~If you are using v1.0.0 then its missing "Cardinal Components" from its fabric.mod.json file so it will continue loading the game even if cardinal components is missing. Try updating to v1.0.1 and it will probably complain about cardinal components being missing as it is required for the mod to function.~~

Edit: The crash report suggests that you have version 3.0.0 of cardinal components. The only advice I could give is to update to the latest version which appears to be 3.1.1.

**Comment by warlock1984** [comment]
install of cardinal components 3.1.1 fix it. tnx for nice mod

**Comment by mrmelon54** [comment]
good :+1:
