### ISSUE TITLE
Crash when placing reciever

### ISSUE THREAD

**Issue by AlisterGontineac** [MrMelon54/wireless-redstone-fabric#2]
https://bytebin.lucko.me/2LjbkDLrgX

https://crashy.net/gU7pcU9FOjWTLfzW00aI

**Comment by mrmelon54** [comment]
looks like you have and outdated version of cardinal components

go check the message at the top of the description

**Comment by AlisterGontineac** [comment]
Huh.. added the cardinal components and got a new crash when trying to enter a world.

https://bytebin.lucko.me/MYXwu0Yg8Q

https://crashy.net/gicaNoed2LR9jSjPpSho
