### ISSUE TITLE
keypad system? (Suggestion/enhancement)

### ISSUE THREAD

**Issue by edl411** [MrMelon54/wireless-redstone-fabric#7]
I wanted to suggest a keypad system as an addition to Wireless Redstone that could add more security to one's base. It would be a small object about the size of an item frame that you can place on blocks. Upon right clicking the keypad, it would open up a prompt where you can input a specific frequency that would activate a receiver that is on the same frequency. There could be a button at the bottom of the prompt screen that, when pressed, sends out the frequency signal. Shift + right clicking with the wireless remote sets the frequency required in order for the keypad to activate its corresponding receiver.

I am not one who plays multiplayer minecraft, but I do have concern that the keypad system could be abused in multiplayer to unlock other players' bases, especially from afar. To remedy this issue, perhaps it could be made as to how far the keypad and receiver send out and accept signals respectively. For example, the receiver could be set that it only accepts the same frequencies sent from no more than 5 blocks away, only accepts the exact frequency sent out from a keypad with a specific name (which the person who created the keypad can set in an anvil and only they can see), etc.

**Comment by mrmelon54** [comment]
I think a better system would be to shift+right click the wireless remote on a "locked receiver block" and it syncs the wireless remote with that specific "locked receiver block" and will only activate it within "X chunks" of the locked receiver. And only a short pulse when right clicking maybe design some circuit to toggle a door opening or something?

What do you think of that idea?

**Comment by edl411** [comment]
The system I was imagining was so that the user doesn't have to keep pulling out their remote to get into their base. You could integrate the remote with the "panel" or whatever you'd like to call it so that only the person who had the remote can activate the system. They can just press on the panel and get into their base without having to worry about anyone else breaking in.

**Comment by edl411** [comment]
My original idea was something similar to Security Craft's keypad system, but integrated with Wireless Redstone. Unfortunately that mod is not available on Fabric.

**Comment by mrmelon54** [comment]
Ok I'll do both ideas then :+1:

**Comment by edl411** [comment]
Will the addition be available on 1.19.2? I use Create Fabric and it hasn't been updated beyond that.

**Comment by mrmelon54** [comment]
unfortunately create fabric is waiting on create to update to 1.19.3 first lol
by the time I get around to adding this suggestion maybe they will have updated them?

**Comment by edl411** [comment]
It's whatever really, I have dozens of mods and it's always a bit annoying to have to redownload them all lol. I lost a mod that I liked after updating from 1.18.2 to 1.19.2 because it got removed from curseforge for some reason.

**Comment by mrmelon54** [comment]
what mod was that?

**Comment by edl411** [comment]
It was basically just a port of the Secret Rooms mod from Forge to Fabric

**Comment by mrmelon54** [comment]
Moved to https://github.com/mrmelon54/wireless_redstone/issues/1
